<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { CirclePlus, Connection, Refresh } from '@element-plus/icons-vue'
import { adminApi, errorMessage } from '../api/client'
import StatusBadge from '../components/StatusBadge.vue'
import type { AdminTask, AdminUser, Dashboard, ModelNode, Prompt, TaskStatus } from '../types'
import { validateModel, validateNewUser, validatePrompt } from './form-validation'
const active = ref('dashboard'), dashboard = ref<Dashboard>(), users = ref<AdminUser[]>([]), models = ref<ModelNode[]>([]), prompts = ref<Prompt[]>([]), tasks = ref<AdminTask[]>([]), taskStatus = ref<TaskStatus | ''>(''), loading = ref(false)
const userDialog = ref(false), modelDialog = ref(false), promptDialog = ref(false), editingModel = ref<string>(), editingPrompt = ref<string>()
const userForm = reactive({ username: '', password: '', role: 'user' }), modelForm = reactive({ display_name: '', model_identifier: '', base_url: '', api_key: '', timeout_seconds: 120, is_enabled: true, description: '' }), promptBody = ref('')
const date = (value: string) => new Date(value).toLocaleString('zh-CN', { hour12: false })
async function load() { loading.value = true; try { const [d, u, m, p, t] = await Promise.all([adminApi.dashboard(), adminApi.users(), adminApi.models(), adminApi.prompts(), adminApi.tasks(taskStatus.value)]); dashboard.value = d.data; users.value = u.data; models.value = m.data; prompts.value = p.data; tasks.value = t.data } catch (e) { ElMessage.error(errorMessage(e)) } finally { loading.value = false } }
async function createUser() { const message = validateNewUser(userForm); if (message) return ElMessage.warning(message); try { await adminApi.createUser(userForm); userDialog.value = false; Object.assign(userForm, { username: '', password: '', role: 'user' }); await load(); ElMessage.success('用户已创建') } catch (e) { ElMessage.error(errorMessage(e)) } }
async function toggleUser(row: AdminUser) { try { await adminApi.enableUser(row.id, !row.is_enabled); await load() } catch (e) { ElMessage.error(errorMessage(e)) } }
async function resetPassword(row: AdminUser) { try { const { value } = await ElMessageBox.prompt('请输入至少 12 位的新密码', `重置 ${row.username} 的密码`, { inputType: 'password', inputValidator: (v) => v.length >= 12 || '密码至少 12 位' }); await adminApi.resetPassword(row.id, value); ElMessage.success('密码已重置') } catch (e) { if (e !== 'cancel') ElMessage.error(errorMessage(e)) } }
function openModel(row?: ModelNode) { editingModel.value = row?.id; Object.assign(modelForm, row ? { ...row, api_key: row.api_key || '' } : { display_name: '', model_identifier: '', base_url: '', api_key: '', timeout_seconds: 120, is_enabled: true, description: '' }); modelDialog.value = true }
async function saveModel() { const message = validateModel(modelForm); if (message) return ElMessage.warning(message); try { await adminApi.saveModel({ ...modelForm, api_key: modelForm.api_key || undefined }, editingModel.value); modelDialog.value = false; await load(); ElMessage.success('模型配置已保存') } catch (e) { ElMessage.error(errorMessage(e)) } }
async function toggleModel(row: ModelNode) { try { await adminApi.enableModel(row.id, !row.is_enabled); await load() } catch (e) { ElMessage.error(errorMessage(e)) } }
async function setDefaultModel(row: ModelNode) { try { await adminApi.defaultModel(row.id); await load(); ElMessage.success('默认模型已更新') } catch (e) { ElMessage.error(errorMessage(e)) } }
async function removeModel(id: string) { try { await ElMessageBox.confirm('确认删除此模型节点？', '删除模型', { type: 'warning' }); await adminApi.deleteModel(id); await load() } catch (e) { if (e !== 'cancel') ElMessage.error(errorMessage(e)) } }
async function health(id: string) { try { await adminApi.modelHealth(id); ElMessage.success('模型服务健康检查通过') } catch (e) { ElMessage.error(errorMessage(e)) } }
function openPrompt(row?: Prompt) { editingPrompt.value = row?.id; promptBody.value = row?.body || ''; promptDialog.value = true }
async function savePrompt() { const message = validatePrompt(promptBody.value); if (message) return ElMessage.warning(message); try { if (editingPrompt.value) await adminApi.updatePrompt(editingPrompt.value, promptBody.value); else await adminApi.createPrompt(promptBody.value); promptDialog.value = false; promptBody.value = ''; editingPrompt.value = undefined; await load(); ElMessage.success('提示词版本已保存') } catch (e) { ElMessage.error(errorMessage(e)) } }
async function activatePrompt(id: string) { try { await adminApi.activatePrompt(id); await load(); ElMessage.success('提示词版本已启用') } catch (e) { ElMessage.error(errorMessage(e)) } }
async function removePrompt(row: Prompt) { try { await ElMessageBox.confirm('删除后无法恢复，确认删除此提示词版本？', '删除提示词', { type: 'warning' }); await adminApi.deletePrompt(row.id); await load(); ElMessage.success('提示词版本已删除') } catch (e) { if (e !== 'cancel') ElMessage.error(errorMessage(e)) } }
onMounted(load)
</script>
<template><section><header class="page-header"><div><h1>后台管理</h1><p>集中管理用户、模型节点、提示词版本和审查任务。</p></div><el-button class="refresh-action" :loading="loading" :icon="Refresh" @click="load">刷新</el-button></header>
<div class="panel glass admin-panel"><el-tabs v-model="active">
<el-tab-pane label="运行概览" name="dashboard"><div v-if="dashboard" class="admin-metrics"><div><span>全部用户</span><b>{{ dashboard.users }}</b><small>{{ dashboard.enabled_users }} 个启用</small></div><div><span>模型节点</span><b>{{ dashboard.models }}</b><small>{{ dashboard.enabled_models }} 个在线配置</small></div><div><span>审查任务</span><b>{{ dashboard.tasks }}</b><small>{{ dashboard.completed_tasks }} 个已完成</small></div><div><span>异常任务</span><b>{{ dashboard.failed_tasks }}</b><small>{{ dashboard.running_tasks }} 个运行中</small></div></div></el-tab-pane>
<el-tab-pane label="用户管理" name="users"><div class="table-tools"><span>账号与权限隔离</span><el-button type="primary" :icon="CirclePlus" @click="userDialog = true">新增用户</el-button></div><el-table :data="users"><el-table-column prop="username" label="用户名" /><el-table-column prop="role" label="角色" width="110" /><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.is_enabled ? 'success' : 'info'">{{ row.is_enabled ? '启用' : '禁用' }}</el-tag></template></el-table-column><el-table-column label="创建时间" width="180"><template #default="{ row }">{{ date(row.created_at) }}</template></el-table-column><el-table-column label="操作" width="220"><template #default="{ row }"><el-button link type="primary" @click="toggleUser(row)">{{ row.is_enabled ? '禁用' : '启用' }}</el-button><el-button link type="primary" @click="resetPassword(row)">重置密码</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="模型节点" name="models"><div class="table-tools"><span>分布式 VLLM 推理服务配置</span><el-button type="primary" :icon="CirclePlus" @click="openModel()">新增模型</el-button></div><el-table :data="models"><el-table-column prop="display_name" label="模型名称" /><el-table-column prop="model_identifier" label="模型标识" min-width="180" /><el-table-column prop="base_url" label="服务地址" min-width="200" /><el-table-column label="状态" width="150"><template #default="{ row }"><el-tag :type="row.is_enabled ? 'success' : 'info'">{{ row.is_enabled ? '启用' : '禁用' }}</el-tag><el-tag v-if="row.is_default" class="model-default-tag">默认</el-tag></template></el-table-column><el-table-column label="操作" width="355"><template #default="{ row }"><el-button link :icon="Connection" @click="health(row.id)">检测</el-button><el-button link type="primary" :disabled="row.is_default || !row.is_enabled" @click="setDefaultModel(row)">设为默认</el-button><el-button link type="primary" @click="toggleModel(row)">{{ row.is_enabled ? '禁用' : '启用' }}</el-button><el-button link type="primary" @click="openModel(row)">编辑</el-button><el-button link type="danger" @click="removeModel(row.id)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="提示词" name="prompts"><div class="table-tools"><span>C 语言专属审查规则版本</span><el-button type="primary" :icon="CirclePlus" @click="openPrompt()">新增版本</el-button></div><el-table :data="prompts"><el-table-column prop="version" label="版本" width="90" /><el-table-column prop="body" label="提示词内容" show-overflow-tooltip /><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.is_active ? 'success' : 'info'">{{ row.is_active ? '当前启用' : '历史版本' }}</el-tag></template></el-table-column><el-table-column label="创建时间" width="180"><template #default="{ row }">{{ date(row.created_at) }}</template></el-table-column><el-table-column label="操作" width="210"><template #default="{ row }"><el-button link type="primary" :disabled="row.is_active" @click="activatePrompt(row.id)">启用</el-button><el-button link type="primary" @click="openPrompt(row)">修改</el-button><el-button link type="danger" :disabled="row.is_active || prompts.length <= 1" @click="removePrompt(row)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="任务监控" name="tasks"><div class="table-tools"><span>全局审查任务状态</span><el-select v-model="taskStatus" clearable placeholder="全部状态" @change="load"><el-option label="排队中" value="queued" /><el-option label="审查中" value="running" /><el-option label="已完成" value="completed" /><el-option label="失败" value="failed" /></el-select></div><el-table :data="tasks"><el-table-column prop="display_name" label="任务" /><el-table-column prop="owner_id" label="用户 ID" min-width="170" /><el-table-column label="状态" width="110"><template #default="{ row }"><StatusBadge :status="row.status" /></template></el-table-column><el-table-column prop="progress" label="进度" width="80" /><el-table-column prop="finding_count" label="问题" width="80" /><el-table-column label="创建时间" width="180"><template #default="{ row }">{{ date(row.created_at) }}</template></el-table-column></el-table></el-tab-pane>
</el-tabs></div>
<el-dialog v-model="userDialog" title="新增用户" width="460"><el-form label-position="top"><el-form-item label="用户名"><el-input v-model="userForm.username" /></el-form-item><el-form-item label="初始密码"><el-input v-model="userForm.password" type="password" show-password placeholder="至少 12 位" /></el-form-item><el-form-item label="角色"><el-select v-model="userForm.role"><el-option label="普通用户" value="user" /><el-option label="管理员" value="admin" /></el-select></el-form-item></el-form><template #footer><el-button @click="userDialog = false">取消</el-button><el-button type="primary" @click="createUser">创建</el-button></template></el-dialog>
<el-dialog v-model="modelDialog" :title="editingModel ? '编辑模型' : '新增模型'" width="580"><el-form label-position="top"><el-form-item label="展示名称"><el-input v-model="modelForm.display_name" /></el-form-item><el-form-item label="模型标识"><el-input v-model="modelForm.model_identifier" /></el-form-item><el-form-item label="VLLM 服务地址"><el-input v-model="modelForm.base_url" /></el-form-item><el-form-item label="API Key（可选）"><el-input v-model="modelForm.api_key" type="password" show-password /></el-form-item><el-form-item label="超时时间（秒）"><el-input-number v-model="modelForm.timeout_seconds" :min="1" :max="3600" /></el-form-item><el-form-item label="说明"><el-input v-model="modelForm.description" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="modelDialog = false">取消</el-button><el-button type="primary" @click="saveModel">保存</el-button></template></el-dialog>
<el-dialog v-model="promptDialog" :title="editingPrompt ? '修改提示词版本' : '新增提示词版本'" width="680"><el-input v-model="promptBody" type="textarea" :rows="14" placeholder="请输入完整的 C 语言审查提示词..." /><template #footer><el-button @click="promptDialog = false">取消</el-button><el-button type="primary" @click="savePrompt">{{ editingPrompt ? '保存修改' : '创建版本' }}</el-button></template></el-dialog>
</section></template>
