<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Delete, Download, Refresh, Search, View } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { errorMessage, reportApi, reviewApi } from '../api/client'
import StatusBadge from '../components/StatusBadge.vue'
import type { ModelNode, ReviewTask } from '../types'
const filters = reactive({ keyword: '', status: '', model_node_id: '', severity: '' }), dateRange = ref<[Date, Date] | null>(null), tasks = ref<ReviewTask[]>([]), models = ref<ModelNode[]>([]), loading = ref(false), router = useRouter()
const date = (value: string) => new Date(value).toLocaleString('zh-CN', { hour12: false })
const duration = (value?: number | null) => value ? `${(value / 1000).toFixed(1)}s` : '--'
const modelName = (id: string) => models.value.find((model) => model.id === id)?.display_name || id
async function load() { loading.value = true; try { tasks.value = (await reviewApi.list({ ...filters, start_time: dateRange.value?.[0].toISOString(), end_time: dateRange.value?.[1].toISOString() })).data } catch (e) { ElMessage.error(errorMessage(e)) } finally { loading.value = false } }
async function remove(id: string) { try { await ElMessageBox.confirm('删除后无法恢复，确认继续？', '删除审查记录', { type: 'warning' }); await reviewApi.remove(id); await load(); ElMessage.success('记录已删除') } catch (e) { if (e !== 'cancel') ElMessage.error(errorMessage(e)) } }
function open(task: ReviewTask) { task.report_id ? router.push(`/reports/${task.report_id}`) : ElMessage.warning('报告暂不可用，请稍后刷新列表') }
async function download(task: ReviewTask, format: 'markdown' | 'pdf') { if (!task.report_id) return; try { const { data } = await reportApi.download(task.report_id, format); const url = URL.createObjectURL(data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `report-${task.report_id}.${format === 'markdown' ? 'md' : 'pdf'}`; document.body.append(anchor); anchor.click(); anchor.remove(); setTimeout(() => URL.revokeObjectURL(url), 0) } catch (e) { ElMessage.error(errorMessage(e)) } }
onMounted(async () => { try { models.value = (await reviewApi.models()).data } catch {} await load() })
</script>
<template><section><header class="page-header"><div><h1>历史报告</h1><p>筛选、回看与管理个人代码审查记录。</p></div><el-button :icon="Refresh" @click="load">刷新</el-button></header><div class="panel glass"><div class="filter-bar"><el-input v-model="filters.keyword" placeholder="搜索任务名称" :prefix-icon="Search" clearable /><el-select v-model="filters.status" placeholder="任务状态" clearable><el-option label="排队中" value="queued" /><el-option label="审查中" value="running" /><el-option label="已完成" value="completed" /><el-option label="失败" value="failed" /></el-select><el-select v-model="filters.model_node_id" placeholder="模型" clearable><el-option v-for="model in models" :key="model.id" :label="model.display_name" :value="model.id" /></el-select><el-select v-model="filters.severity" placeholder="风险等级" clearable><el-option label="高危" value="high" /><el-option label="中危" value="medium" /><el-option label="低危" value="low" /><el-option label="建议" value="suggestion" /></el-select><el-date-picker v-model="dateRange" type="daterange" start-placeholder="开始日期" end-placeholder="结束日期" range-separator="至" /><el-button type="primary" @click="load">筛选</el-button></div><el-table class="history-table" :data="tasks" v-loading="loading"><el-table-column prop="display_name" label="任务名称" min-width="180" /><el-table-column label="模型" min-width="160"><template #default="{ row }">{{ modelName(row.model_node_id) }}</template></el-table-column><el-table-column prop="input_mode" label="提交方式" width="100" /><el-table-column label="状态" width="110"><template #default="{ row }"><StatusBadge :status="row.status" /></template></el-table-column><el-table-column prop="file_count" label="文件" width="70" /><el-table-column prop="finding_count" label="问题" width="70" /><el-table-column label="耗时" width="80"><template #default="{ row }">{{ duration(row.duration_ms) }}</template></el-table-column><el-table-column label="创建时间" width="170"><template #default="{ row }">{{ date(row.created_at) }}</template></el-table-column><el-table-column label="操作" fixed="right" width="260"><template #default="{ row }"><span class="history-actions"><el-button link type="primary" :icon="View" :disabled="row.status !== 'completed'" @click="open(row)">查看</el-button><el-button link type="primary" :icon="Download" :disabled="row.status !== 'completed'" @click="download(row, 'markdown')">MD</el-button><el-button link type="primary" :icon="Download" :disabled="row.status !== 'completed'" @click="download(row, 'pdf')">PDF</el-button><el-button link type="danger" :icon="Delete" @click="remove(row.id)">删除</el-button></span></template></el-table-column></el-table></div></section></template>
